name: CI

on: [ push, pull_request ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v3

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          php_version: 7.4
          bootstrap: tests/bootstrap.php
          configuration: phpunit.xml